### ISSUE TITLE
change to set sub-sample of overall lengths

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#2]
https://github.com/BenWilliams-NOAA/swo/blob/a22e0d57e173f3d1f8103357e5894089969298f7/R/sample.R#L17
from here to line 44 change to:

    lfreq_un %>%
      tidytable::mutate.(id = .I) %>%
      tidytable::mutate.(n = .N, 
                         .by = c(year, species_code, stratum, hauljoin)) -> .inter
    
    # sample by sample size
    .inter %>%
      dplyr::group_by(year, species_code, stratum, hauljoin) %>%
      dplyr::sample_n(if(n > samples) samples else n) -> .new_samp
    
    if(isTRUE(write_sample)){
      .new_samp %>% 
        dplyr::group_by(year, species_code, stratum, hauljoin) %>%
        dplyr::count() %>% 
        vroom::vroom_write(here::here("output", region, paste0(save, "_removed_length.csv")), delim = ",")
    }
    
    .new_samp

**Comment by BenWilliams-NOAA** [comment]
implemented at `reduce_lengths` default is `NULL` enter an integer to set the number of lengths to keep - works similar to the `sample` function in that it keeps all lengths < sample size and shuffles lengths > samples size
