### ISSUE TITLE
write_sample error

### ISSUE THREAD

**Issue by mdbryan** [BenWilliams-NOAA/swo#3]
When I set write_sample=TRUE I  get the following error:
  Error in sample(.lfreq_un, samples = length_samples, write_sample = write_sample,  : 
  unused argument (write_sample = write_sample)
I re-installed the swo package on 4/25/2022 at 12:25pm to make sure I was not using an older version. I am still encountering the error. 
I think the sample.R code is missing write_sample. write_sample = write sample on line 62 of swo_sim.R and again on line 93 of swo.R.
Line 93 calls the sample function, which seems to be missing the write_sample argument.

**Comment by BenWilliams-NOAA** [comment]
Should be corrected now
