### ISSUE TITLE
found length pop'n ests bug

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#35]
https://github.com/BenWilliams-NOAA/swo/blob/55cdd500418fdb4df558cf87a5a1167cb11729db/R/lpop.R#L17

change this to:

.cpue %>% 
  tidytable::drop_na.(catchjoin) %>% 
  tidytable::select.(species_code, hauljoin, stratum) %>% 
  tidytable::mutate.(pair_c = paste0(hauljoin, "-", species_code)) %>% 
  tidytable::select.(pair_c) -> hls_c

.lcomp %>%
  tidytable::summarise.(hauljoin_l = unique(hauljoin),
                        .by = c(species_code, stratum)) %>% 
  tidytable::mutate.(pair_l = paste0(hauljoin_l, "-", species_code)) %>% 
  tidytable::select.(pair_l) -> hls_l

.cpue %>% 
  tidytable::drop_na.(catchjoin) %>% 
  tidytable::filter.(which(hls_c$pair_c %in% hls_l$pair_l == FALSE)) -> .no_length

basically what's going on is that the tidytable::filter.() function isn't working like you'd think it should. for example, say you have two species that are both caught on a certain haul, one gets sampled for lengths and the other doesn't. what the original code does is it doesn't identify that haul in the .no_length data for the species that wasn't sampled for length because there was a species that was sampled for length. doing .by = c(species_code, ...) doesn't work either, neither does group_by(species_code, ...) %<% dplyr::filter (just does the same thing as tidytable::filter.). fyi, i tried a bunch of groupings to see if i coud get it to work, cause the way it was originally written it should work on a species-by-species basis. this fairly long hand way of doing it get's the swo() fcn to match up with what race produces (albeit, this only effects a few years and is a small bug, but should change it before having gap dig in, or bringing issues up to gap).

**Comment by pete-hulson** [comment]
And, for an example - look at pollock and pop in 2007 stratum 10. there's a haul in there that caught both but only sampled pollock for lengths, but, it isn't recognized for pop as a no length haul

**Comment by BenWilliams-NOAA** [comment]
smoothed over the code a bit, but should now produce the same results as what you proposed
