### ISSUE TITLE
add race pop'n ests

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#37]
https://github.com/BenWilliams-NOAA/swo/blob/55cdd500418fdb4df558cf87a5a1167cb11729db/R/query_data.R#L235

swap this section with:

    # length pop
    rp = sql_read('race_pop.sql')
    rp = sql_add(paste0(region, '.SIZECOMP_TOTAL'), rp)
    rp = sql_filter(sql_precode = 'IN', sql_code = rp,
                    x = species, 
                    flag = '-- insert species')
    rp = sql_filter(sql_precode = ">=", x = yrs, 
                    sql_code = rp, flag = '-- insert year')
    
  
    sql_run(afsc, rp) %>% 
      dplyr::rename_all(tolower) %>% 
      vroom::vroom_write(., 
                         here::here('data', paste0("race_lpop_", tolower(region), ".csv")), 
                         delim = ',')
    # age pop
    rp = sql_read('race_apop.sql')
    rp = sql_add(paste0(region, '.AGECOMP_TOTAL'), rp)
    rp = sql_filter(sql_precode = 'IN', sql_code = rp,
                    x = species, 
                    flag = '-- insert species')
    rp = sql_filter(sql_precode = ">=", x = yrs, 
                    sql_code = rp, flag = '-- insert year')
    
    
    sql_run(afsc, rp) %>% 
      dplyr::rename_all(tolower) %>% 
      vroom::vroom_write(., 
                         here::here('data', paste0("race_apop_", tolower(region), ".csv")), 
                         delim = ',') 

to add in call to age pop'n estimates from race (and rename length pop estimates to distinguish from age). i'll email the sql file to add to inst/sql ('race_apop.sql'). the only difference between that and the race_pop.sql is that in the SIZECOMP_TOTAL the column is year, and in AGECOMP_TOTAL the column is survey_year

**Comment by BenWilliams-NOAA** [comment]
no need for the raec_apop.sql - just used the one already there. added this, but seems something similar will be needed for the BS - no?

**Comment by pete-hulson** [comment]
i think we may need someting for bs, not sure what table is. can't use the race_pop.sql for age ests tho, in the length table the year column is 'year', in the age table the year column is 'survey_year' - this was the original way i tried it until it crashed trying to pull data

**Comment by BenWilliams-NOAA** [comment]
completed
