### ISSUE TITLE
gotta change to map

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#42]
https://github.com/BenWilliams-NOAA/swo/blob/dff28a2389e9e55cf3fb663fca2e433147844682/R/swo_sim.R#L63
get an error saying rerun is deprecated, change to rr <- purrr::map(1:iters, ~ swo(...

**Comment by pete-hulson** [comment]
oh, and i don't think we need to worry about all the special cases (which would need to be changed too) - i think we can just stick with the main species

**Comment by BenWilliams-NOAA** [comment]
yeah - caught that in the iss, but forgot it here - should be covered now
