### ISSUE TITLE
replace with...

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#44]
https://github.com/BenWilliams-NOAA/swo/blob/cf541e1542e62add976169d95b42569ba619636f/R/swo_sim.R#L110

last issue got too screwy, so am doing this new one. if you replace this line with:

  # compute harmonic mean of ess and write out input sample size results
  ess_size %>% 
    tidytable::mutate.(iss = psych::harmonic.mean(value), 
                       .by = c(year, species_code, ess)) %>%
    dplyr::distinct(year, species_code, ess, iss) %>% 
    tidytable::drop_na.() %>% 
    tidytable::filter.(iss > 0) %>% 
    tidytable::rename.(comp_type = ess) %>% 
    tidytable::mutate.(comp_type = case_when(comp_type == 'ess_f' ~ 'female',
                                             comp_type == 'ess_m' ~ 'male',
                                             comp_type == 'ess_t' ~ 'total')) -> iss_size
  
  ess_age %>% 
    tidytable::mutate.(iss = psych::harmonic.mean(value), 
                       .by = c(year, species_code, ess)) %>%
    dplyr::distinct(year, species_code, ess, iss) %>% 
    tidytable::drop_na.() %>% 
    tidytable::filter.(iss > 0) %>% 
    tidytable::rename.(comp_type = ess) %>% 
    tidytable::mutate.(comp_type = case_when(comp_type == 'ess_f' ~ 'female',
                                             comp_type == 'ess_m' ~ 'male',
                                             comp_type == 'ess_t' ~ 'total')) -> iss_age
  
  vroom::vroom_write(iss_size, here::here("output", paste0(save, "_iss_sz.csv")), delim = ",")    
  vroom::vroom_write(iss_age, here::here("output", paste0(save, "_iss_ag.csv")), delim = ",")

then we won't have to run the harmonic mean calcs after the fact

**Comment by pete-hulson** [comment]
one more try, need region in those vroom commands, so change those last two lines to:

  vroom::vroom_write(iss_size, here::here("output", region, paste0(save, "_iss_sz.csv")), delim = ",")    
  vroom::vroom_write(iss_age, here::here("output", region, paste0(save, "_iss_ag.csv")), delim = ",")

**Comment by BenWilliams-NOAA** [comment]
do you really want to change the output of swo - thinking of downstream effects of previous analyses?

**Comment by pete-hulson** [comment]
that's a good point - in this case it doesn't really take anything away from what we previously had (like being able to plot the replicated ess), and the plot code for the input sample size stuff would become simpler (in that we don't need to compute it within the ggplot lines but can just read these results in and plot). i dunno tho, six-one-half-dozen thing i guess
