### ISSUE TITLE
take care of duplicate hauls the right way

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#48]
https://github.com/BenWilliams-NOAA/swo/blob/f4ea1460e9ba51842b64e965320e10fb473077c9/R/swo.R#L68
from here to line 79 change to:

    boot_haul(.cpue) %>% 
      tidytable::mutate.(hauljoin_unq = .I) -> .hls
    
    .hls %>% 
      tidytable::left_join.(.cpue) %>% 
      tidytable::rename(hauljoin_orig = 'hauljoin',
                        hauljoin = 'hauljoin_unq') -> .cpue
    .hls %>% 
      tidytable::left_join.(.lfreq) %>% 
      tidytable::rename(hauljoin_orig = 'hauljoin',
                        hauljoin = 'hauljoin_unq') -> .lfreq
    .hls %>% 
      tidytable::left_join.(.lfreq_un) %>% 
      tidytable::drop_na.() %>% 
      tidytable::rename(hauljoin_orig = 'hauljoin',
                        hauljoin = 'hauljoin_unq') -> .lfreq_un
    .hls %>% 
      tidytable::left_join.(.agedat) %>% 
      tidytable::drop_na.() %>% 
      tidytable::rename(hauljoin_orig = 'hauljoin',
                        hauljoin = 'hauljoin_unq') -> .agedat

**Comment by BenWilliams-NOAA** [comment]
business: taken care of
