### ISSUE TITLE
to remove NAs

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#5]
https://github.com/BenWilliams-NOAA/swo/blob/d38437092b735385384a00ad0451b78872abfd14/R/apop.R#L27

after this line add:

    tidytable::filter.(is.na(sizepop) == FALSE) %>% 

will remove NAs that occur in age pop'n ests when length is in specimen data but not in length frequency data - I think this occurs when they sample a really big fish to get an age, but since the lfreq and specimen data don't talk to one another you don't get those extreme lengths in the lfreq. That, or (since I found this with pollock) they mislabeled a big cod as a REALLY big pollock

**Comment by BenWilliams-NOAA** [comment]
i put `tidytable::drop_na.()` in there, haven't checked it though
