### ISSUE TITLE
gotta add me

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#50]
tried to push and got this:
![image](https://user-images.githubusercontent.com/5578975/235226581-8c303d36-3e93-407e-8bf5-da324a5a534c.png)
i got git denied

**Comment by BenWilliams-NOAA** [comment]
Yeah it’s asking for a pull request instead of a push since I never have direct accessOn Apr 28, 2023, at 10:35 AM, Pete Hulson ***@***.***> wrote:﻿
tried to push and got this:

i got git denied
