### ISSUE TITLE
change to dplyr

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/swo#7]
https://github.com/BenWilliams-NOAA/swo/blob/624c9f647822e7169e607373a784fde721fdc05d/R/apop.R#L23

need to change this and following line to:

    dplyr::group_by(year, species_code, sex, length, age) %>%
    dplyr::summarise(age_num = length(age))

I'm not sure why, but the tidytable::summarise. isn't actually getting the length of the age, it's just returning 1, which is then screwing things up

**Comment by BenWilliams-NOAA** [comment]
done
